<?php
return apply_filters('mprm_admin_vars', array(
		"delete_img" => esc_html__('Delete Image', 'mp-restaurant-menu'),
		"delete" => esc_html__('Delete', 'mp-restaurant-menu'),
		"insert_media" => esc_html__('Insert a media', 'mp-restaurant-menu'),
		"insert" => esc_html__('Insert', 'mp-restaurant-menu'),
		"choose_image" => esc_html__('Choose an image', 'mp-restaurant-menu'),
		"use_image" => esc_html__('Select', 'mp-restaurant-menu'),
		"shortcode_title" => esc_html__('Insert Restaurant Menu Shortcode', 'mp-restaurant-menu'),
		"cancel" => esc_html__('Cancel', 'mp-restaurant-menu'),
		"choose" => esc_html__('Choose', 'mp-restaurant-menu'),
		'mprm_version' => mprm_get_plugin_version(),
		'add_new_menu_item' => esc_html__('Add New Menu item', 'mp-restaurant-menu'),
		'use_this_file' => esc_html__('Use This File', 'mp-restaurant-menu'),
		'quick_edit_warning' => esc_html__('Sorry, not available for variable priced products.', 'mp-restaurant-menu'),
		'delete_payment' => esc_html__('Are you sure you wish to delete this payment?', 'mp-restaurant-menu'),
		'delete_payment_note' => esc_html__('Are you sure you wish to delete this note?', 'mp-restaurant-menu'),
		'resend_receipt' => esc_html__('Are you sure you wish to resend the purchase receipt?', 'mp-restaurant-menu'),
		'delete_payment_menu_item' => esc_html__('Are you sure you wish to delete this item?', 'mp-restaurant-menu'),
		'one_price_min' => esc_html__('You must have at least one price', 'mp-restaurant-menu'),
		'one_field_min' => esc_html__('You must have at least one field', 'mp-restaurant-menu'),
		'one_menu_item_min' => esc_html__('Orders must contain at least one item', 'mp-restaurant-menu'),
		'one_option' => esc_html__('Choose an item', 'mp-restaurant-menu'),
		'one_or_more_option' => esc_html__('Choose one or more items', 'mp-restaurant-menu'),
		'numeric_item_price' => esc_html__('Item price must be numeric', 'mp-restaurant-menu'),
		'numeric_quantity' => esc_html__('Quantity must be numeric', 'mp-restaurant-menu'),
		'numeric_tax' => esc_html__('Tax must be numeric', 'mp-restaurant-menu'),
		'currency' => mprm_get_currency(),
		'rate' => mprm_get_option('tax_rate', 0),
		'enable_taxes' => mprm_get_option('enable_taxes', 0),
		'currency_sign' => mprm_currency_filter(''),
		'currency_pos' => mprm_get_option('currency_position', 'before'),
		'currency_decimals' => mprm_currency_decimal_filter(),
		'new_media_ui' => apply_filters('mprm_use_35_media_ui', 1),
		'remove_text' => esc_html__('Remove', 'mp-restaurant-menu'),
		'type_to_search' => esc_html__('Type to search', 'mp-restaurant-menu'),
		'quantities_enabled' => mprm_item_quantities_enabled(),
		'batch_export_no_class' => esc_html__('You must choose a method.', 'mp-restaurant-menu'),
		'batch_export_no_reqs' => esc_html__('Required fields not completed.', 'mp-restaurant-menu'),
		'reset_stats_warn' => __('Are you sure you want to reset your store? This process is <strong><em>not reversible</em></strong>. Please be sure you have a recent backup.', 'mp-restaurant-menu'),
	)
);
